// mix_fastapi/frontend/src/components/MetricCard.vue
<template>
  <Card class="hover:shadow-lg transition-shadow">
    <template #header>
      <div class="flex items-start justify-between p-6 pb-2">
        <div>
          <p class="text-sm font-medium text-gray-600">{{ title }}</p>
          <p class="text-3xl font-bold text-gray-900 mt-2">{{ value }}</p>
        </div>
        <div class="rounded-lg bg-blue-50 p-3">
          <component :is="icon" class="h-6 w-6 text-blue-600" />
        </div>
      </div>
    </template>
    <template #content>
      <div v-if="subtitle" class="text-xs text-gray-500 pb-2">
        {{ subtitle }}
      </div>
      <div v-if="trend" class="flex items-center text-sm">
        <span :class="trend === 'up' ? 'text-green-600' : 'text-red-600'">
          {{ trendValue }}
        </span>
      </div>
    </template>
  </Card>
</template>

<script setup lang="ts">
import Card from "primevue/card";

defineProps<{
  title: string;
  value: string | number;
  icon: any;
  trend?: "up" | "down";
  trendValue?: string;
  subtitle?: string;
  className?: string;
}>();
</script>

// mix_fastapi/frontend/src/app/components/metric-card/metric-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-metric-card',
  templateUrl: './metric-card.component.html',
  styleUrls: ['./metric-card.component.css']
})
export class MetricCardComponent {
  @Input() title: string = '';
  @Input() value: string | number = '';
  @Input() subtitle?: string;
  @Input() trend?: 'up' | 'down';
  @Input() trendValue?: string;
  @Input() icon?: string;
}

<div class="card-corporate overflow-hidden">
  <div class="p-6">
    <div class="flex items-center">
      <div class="flex-shrink-0">
        <div class="rounded-xl bg-gradient-to-br from-primary-500 to-primary-600 p-3 shadow-lg">
          <svg *ngIf="!icon" class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
          </svg>
        </div>
      </div>
      <div class="ml-5 w-0 flex-1">
        <dl>
          <dt class="text-sm font-medium text-gray-600 truncate">{{ title }}</dt>
          <dd class="flex items-baseline mt-1">
            <div class="text-3xl font-bold text-gray-900">{{ value }}</div>
            <div *ngIf="trend && trendValue" class="ml-2 flex items-baseline text-sm font-semibold"
                 [class.text-green-600]="trend === 'up'"
                 [class.text-red-600]="trend === 'down'">
              <svg *ngIf="trend === 'up'" class="self-center flex-shrink-0 h-5 w-5 text-green-500" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M5.293 9.707a1 1 0 010-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 01-1.414 1.414L11 7.414V15a1 1 0 11-2 0V7.414L6.707 9.707a1 1 0 01-1.414 0z" clip-rule="evenodd" />
              </svg>
              <svg *ngIf="trend === 'down'" class="self-center flex-shrink-0 h-5 w-5 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M14.707 10.293a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 111.414-1.414L9 12.586V5a1 1 0 012 0v7.586l2.293-2.293a1 1 0 011.414 0z" clip-rule="evenodd" />
              </svg>
              <span class="sr-only">{{ trend === 'up' ? 'Incrementó' : 'Disminuyó' }} en</span>
              {{ trendValue }}
            </div>
          </dd>
        </dl>
      </div>
    </div>
    <p *ngIf="subtitle" class="mt-4 text-sm text-gray-600 border-t border-gray-100 pt-3">{{ subtitle }}</p>
  </div>
</div>
