// Proyecto/client/src/components/StatusBadge.vue
<template>
  <span 
    class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium"
    :class="statusClasses"
  >
    <component :is="statusIcon" class="mr-1 h-3 w-3" />
    {{ label }}
  </span>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { CheckCircle, AlertCircle, XCircle } from "lucide-vue-next";

const props = defineProps<{
  status: "online" | "warning" | "offline";
}>();

const statusConfig = {
  online: {
    label: "Online",
    classes: "bg-green-100 text-green-800",
    icon: CheckCircle,
  },
  warning: {
    label: "Warning",
    classes: "bg-yellow-100 text-yellow-800",
    icon: AlertCircle,
  },
  offline: {
    label: "Offline",
    classes: "bg-red-100 text-red-800",
    icon: XCircle,
  },
};

const config = computed(() => statusConfig[props.status]);
const label = computed(() => config.value.label);
const statusClasses = computed(() => config.value.classes);
const statusIcon = computed(() => config.value.icon);
</script>

// mix_fastapi/frontend/src/app/components/status-badge/status-badge.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-status-badge',
  templateUrl: './status-badge.component.html',
  styleUrls: ['./status-badge.component.css']
})
export class StatusBadgeComponent {
  @Input() status: 'online' | 'offline' | 'warning' = 'offline';

  get badgeClass(): string {
    const baseClass = 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium';
    
    switch (this.status) {
      case 'online':
        return `${baseClass} bg-green-100 text-green-800`;
      case 'offline':
        return `${baseClass} bg-red-100 text-red-800`;
      case 'warning':
        return `${baseClass} bg-yellow-100 text-yellow-800`;
      default:
        return `${baseClass} bg-gray-100 text-gray-800`;
    }
  }

  get displayText(): string {
    return this.status.charAt(0).toUpperCase() + this.status.slice(1);
  }
}

<span [class]="badgeClass">
  <svg class="mr-1.5 h-2 w-2" 
       [class.text-green-400]="status === 'online'"
       [class.text-red-400]="status === 'offline'"
       [class.text-yellow-400]="status === 'warning'"
       fill="currentColor" viewBox="0 0 8 8">
    <circle cx="4" cy="4" r="3" />
  </svg>
  {{ displayText }}
</span>
