// mix_fastapi/frontend/src/components/MetricCard.vue
<template>
  <Card class="hover:shadow-lg transition-shadow">
    <template #header>
      <div class="flex items-start justify-between p-6 pb-2">
        <div>
          <p class="text-sm font-medium text-gray-600">{{ title }}</p>
          <p class="text-3xl font-bold text-gray-900 mt-2">{{ value }}</p>
        </div>
        <div class="rounded-lg bg-blue-50 p-3">
          <component :is="icon" class="h-6 w-6 text-blue-600" />
        </div>
      </div>
    </template>
    <template #content>
      <div v-if="subtitle" class="text-xs text-gray-500 pb-2">
        {{ subtitle }}
      </div>
      <div v-if="trend" class="flex items-center text-sm">
        <span :class="trend === 'up' ? 'text-green-600' : 'text-red-600'">
          {{ trendValue }}
        </span>
      </div>
    </template>
  </Card>
</template>

<script setup lang="ts">
import Card from "primevue/card";

defineProps<{
  title: string;
  value: string | number;
  icon: any;
  trend?: "up" | "down";
  trendValue?: string;
  subtitle?: string;
  className?: string;
}>();
</script>

// mix_fastapi/frontend/src/components/MetricCard.tsx
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import { LucideIcon } from "lucide-react";

interface MetricCardProps {
  title: string;
  value: string | number;
  subtitle?: string;
  icon: LucideIcon;
  trend?: "up" | "down" | "neutral";
  trendValue?: string;
  className?: string;
}

export function MetricCard({ 
  title, 
  value, 
  subtitle, 
  icon: Icon, 
  trend, 
  trendValue,
  className 
}: MetricCardProps) {
  return (
    <Card className={cn("dashboard-card border-l-4 border-l-transparent hover:border-l-primary", className)}>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle className="text-sm font-medium text-muted-foreground">
          {title}
        </CardTitle>
        <Icon className="h-4 w-4 text-muted-foreground/50" />
      </CardHeader>
      <CardContent>
        <div className="flex items-baseline space-x-2">
          <div className="text-2xl font-bold text-gray-900">{value}</div>
          {trend && (
            <span className={cn(
              "text-xs font-medium",
              trend === "up" ? "text-green-600" : 
              trend === "down" ? "text-red-600" : "text-gray-500"
            )}>
              {trend === "up" ? "↑" : trend === "down" ? "↓" : "−"} {trendValue}
            </span>
          )}
        </div>
        {subtitle && (
          <p className="text-xs text-muted-foreground mt-1">
            {subtitle}
          </p>
        )}
      </CardContent>
    </Card>
  );
}
