// Proyecto/client/src/components/Layout.vue
<template>
  <div class="flex h-screen overflow-hidden bg-gray-50">
    <!-- Sidebar -->
    <aside class="hidden w-64 overflow-y-auto bg-white shadow-sm lg:block">
      <div class="flex h-full flex-col">
        <div class="flex h-16 items-center px-6 border-b">
          <Activity class="h-6 w-6 text-blue-600 mr-2" />
          <span class="text-xl font-bold text-gray-900">Monitoreo Infra</span>
        </div>
        <nav class="flex-1 space-y-1 px-3 py-4">
          <router-link 
            v-for="item in navigation" 
            :key="item.name"
            :to="item.path"
            class="nav-link group flex items-center px-3 py-2 text-sm font-medium rounded-lg transition-colors"
            :class="isActive(item.path) ? 'bg-blue-50 text-blue-700' : 'text-gray-700 hover:bg-gray-50'"
          >
            <component :is="item.icon" class="mr-3 h-5 w-5" />
            {{ item.name }}
          </router-link>
        </nav>
      </div>
    </aside>

    <!-- Main Content -->
    <div class="flex flex-1 flex-col overflow-hidden">
      <header class="bg-white shadow-sm lg:hidden">
        <div class="flex h-16 items-center justify-between px-4">
          <Activity class="h-6 w-6 text-blue-600" />
          <span class="text-lg font-bold">Monitoreo Infra</span>
        </div>
      </header>
      
      <main class="flex-1 overflow-y-auto overflow-x-hidden">
        <div class="container mx-auto px-4 py-8 sm:px-6 lg:px-8">
          <slot />
        </div>
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useRoute } from "vue-router";
import { Activity, LayoutDashboard, Database, Server, Monitor, FileText } from "lucide-vue-next";

const route = useRoute();

const navigation = [
  { name: "Dashboard", path: "/", icon: LayoutDashboard },
  { name: "Databases", path: "/databases", icon: Database },
  { name: "Windows Servers", path: "/windows", icon: Server },
  { name: "Linux Servers", path: "/linux", icon: Monitor },
  { name: "Logs", path: "/logs", icon: FileText },
];

const isActive = (path: string) => {
  return route.path === path;
};
</script>

<style scoped>
.nav-link {
  @apply transition-all duration-200;
}
</style>

// vue/frontend/src/components/Layout.tsx
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { useTranslation } from "react-i18next";
import { 
  LayoutDashboard, 
  Database, 
  Monitor, 
  Server, 
  ScrollText, 
  Menu,
  Bell,
  Search,
  Settings,
  Languages
} from "lucide-react";
import { cn } from "@/lib/utils";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";

export function Layout({ children }: { children: React.ReactNode }) {
  const { t, i18n } = useTranslation();
  const [location] = useLocation();
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const navigation = [
    { name: t("nav.dashboard"), href: "/", icon: LayoutDashboard },
    { name: t("nav.databases"), href: "/databases", icon: Database },
    { name: t("nav.windows"), href: "/windows", icon: Monitor },
    { name: t("nav.linux"), href: "/linux", icon: Server },
    { name: t("nav.logs"), href: "/logs", icon: ScrollText },
  ];

  const changeLanguage = (lng: string) => {
    i18n.changeLanguage(lng);
  };

  return (
    <div className="min-h-screen bg-gray-50 flex">
      {/* Mobile Sidebar Overlay */}
      {sidebarOpen && (
        <div 
          className="fixed inset-0 bg-black/20 z-40 lg:hidden"
          onClick={() => setSidebarOpen(false)}
        />
      )}

      {/* Sidebar */}
      <div className={cn(
        "fixed lg:static inset-y-0 left-0 z-50 w-64 bg-white border-r border-gray-200 transform transition-transform duration-200 lg:transform-none flex flex-col",
        sidebarOpen ? "translate-x-0" : "-translate-x-full"
      )}>
        {/* Logo */}
        <div className="h-16 flex items-center px-6 border-b border-gray-100">
          <div className="w-8 h-8 rounded bg-primary flex items-center justify-center mr-3 shadow-md shadow-primary/20">
            <span className="text-white font-bold text-lg">I</span>
          </div>
          <span className="font-bold text-xl tracking-tight text-gray-900">Infra<span className="text-primary">Red</span></span>
        </div>

        {/* Nav */}
        <nav className="flex-1 px-4 py-6 space-y-1">
          {navigation.map((item) => {
            const isActive = location === item.href;
            return (
              <Link key={item.name} href={item.href} className={cn(
                "group flex items-center px-3 py-3 text-sm font-medium rounded-lg transition-all duration-200",
                isActive 
                  ? "bg-red-50 text-primary shadow-sm ring-1 ring-primary/10" 
                  : "text-gray-600 hover:bg-gray-50 hover:text-gray-900"
              )}>
                <item.icon className={cn(
                  "mr-3 h-5 w-5 transition-colors",
                  isActive ? "text-primary" : "text-gray-400 group-hover:text-gray-500"
                )} />
                {item.name}
              </Link>
            );
          })}
        </nav>

        {/* User / Footer */}
        <div className="p-4 border-t border-gray-100">
          <div className="flex items-center">
            <div className="h-8 w-8 rounded-full bg-gray-200 flex items-center justify-center text-xs font-bold text-gray-500">
              AD
            </div>
            <div className="ml-3">
              <p className="text-sm font-medium text-gray-700">Admin User</p>
              <p className="text-xs text-gray-500">DevOps Engineer</p>
            </div>
            <Settings className="ml-auto h-4 w-4 text-gray-400 cursor-pointer hover:text-primary transition-colors" />
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
        {/* Topbar */}
        <header className="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-4 lg:px-8">
          <button 
            onClick={() => setSidebarOpen(true)}
            className="lg:hidden p-2 text-gray-500 hover:bg-gray-100 rounded-md"
          >
            <Menu className="h-6 w-6" />
          </button>

          <div className="flex-1 flex justify-center lg:justify-start lg:ml-4">
            <div className="max-w-lg w-full relative hidden md:block">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Search className="h-4 w-4 text-gray-400" />
              </div>
              <input 
                className="block w-full pl-10 pr-3 py-2 border border-gray-200 rounded-full leading-5 bg-gray-50 placeholder-gray-400 focus:outline-none focus:bg-white focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all sm:text-sm"
                placeholder="Search systems, logs, or metrics..."
              />
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon" className="h-9 w-9">
                  <Languages className="h-5 w-5 text-gray-400" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem onClick={() => changeLanguage('es')}>Español</DropdownMenuItem>
                <DropdownMenuItem onClick={() => changeLanguage('en')}>English</DropdownMenuItem>
                <DropdownMenuItem onClick={() => changeLanguage('pt')}>Português</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>

            <button className="relative p-2 text-gray-400 hover:text-gray-500 transition-colors">
              <Bell className="h-5 w-5" />
              <span className="absolute top-1.5 right-1.5 block h-2 w-2 rounded-full bg-primary ring-2 ring-white"></span>
            </button>
            <div className="h-8 w-px bg-gray-200 mx-2"></div>
            <div className="flex items-center">
              <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                System Healthy
              </span>
            </div>
          </div>
        </header>

        {/* Page Content */}
        <main className="flex-1 overflow-y-auto bg-gray-50 p-4 lg:p-8">
          <div className="max-w-7xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500">
            {children}
          </div>
        </main>
      </div>
    </div>
  );
}
